// src/TechnologyTable.tsx
import * as util from './util.js';
import * as gameLogic from './game.js';
import ResourceCost from "./ResourceCost";

const Technologies = ({technologies}) => {
    return (
        <div id="technologiesContainer">
            <table className="table table-sm table-responsive-sm" id="technologiesTable" style={{textAlign: 'center'}}>
                <tbody>
                <tr className="noTopBorder">
                    <th className="text-left">Technology</th>
                    <th className="text-right">Price</th>
                    <th/>
                </tr>
                {technologies.filter(technology => technology.status !== 'hidden').map(technology => <Technology key={technology.name} technology={technology} />)}
                </tbody>
            </table>
        </div>
    );
}

const Technology = ({technology}) => {
    const makeDiscovery = (technologyName) => {
        // $emit('makeDiscovery', technologyName);
    };

    return (
        <tr>
            <td className="text-left">
                <img src={`ico/${technology.image}`} alt="technology" />
                {technology.name}
            </td>
            <td className="text-right">
                <ResourceCost key={technology.name} coster={technology}/>
            </td>
            <td className="text-left">
                <input type="button" className="btn btn-outline-secondary btn-sm"
                       value={technology.discovered ? 'Discovered' : 'Discover'}
                       disabled={technology.discovered || (technology.cost.amount > technology.amount)}
                       onClick={() => makeDiscovery(technology.name)}/>
            </td>
        </tr>
    );
}

export default Technologies;

// src/TechnologyTable.vue
<template>
    <div id="technologiesContainer">
        <table class="table table-sm table-responsive-sm" id="technologiesTable" style="text-align: center;">
            <tbody>
            <tr class="noTopBorder">
                <th class="text-left">Technology</th><th class="text-right">Price</th><th></th>
            </tr>
            <tr v-for="tech in technologies" v-if="tech.status !== 'hidden'" v-bind:key="tech.name + 'Row'">
                <td class="text-left">
                    <img v-bind:src="'ico/' + tech.image" style="height: 32px;"/>
                    {{ camelToTitle(tech.name) }}
                </td>
                <td class="text-right">
                    <resource-cost
                            v-bind:coster="tech"
                            v-bind:id="tech.name">
                    </resource-cost>
                </td>
                <td class="text-left">
                    <input type="button" class="btn btn-outline-secondary btn-sm"
                           v-bind:value="tech.discovered ? 'Discovered' : 'Discover'"
                           v-bind:disabled="tech.discovered || (tech.cost.amount > research.amount)"
                           v-on:click="makeDiscovery(tech.name)"/>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
    import * as util from './util.js'
    import * as gameLogic from './game.js'

    export default {
        name: 'technology-table',
        props: ['technologies', 'research'],
        data: function () {
            return {
                text: 'some-text'
            }
        },
        methods: {
            camelToTitle: function (value) {
                const result = value.replace(/([A-Z])/g, " $1");
                return result.charAt(0).toUpperCase() + result.slice(1);
            },
            makeDiscovery: function(technologyName){
                this.$emit('makeDiscovery', technologyName);
            },
        }
    }
</script>
